#!/usr/bin/env python3
"""Verify IPALift release artifacts from isolated environments.

The default mode checks archive contents, installs the wheel and source
distribution into separate temporary virtual environments, and exercises the
installed command line. Supplying --ghidra-home additionally runs the complete
pipeline twice from each artifact, validates every JSON artifact, and compares
all generated bytes for determinism.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import plistlib
import struct
import subprocess
import sys
import tarfile
import tempfile
import venv
import zipfile
from pathlib import Path, PurePosixPath
from typing import Iterable

from jsonschema import Draft202012Validator
from referencing import Registry, Resource


VERSION = "0.1.0"
EXPECTED_ANALYSIS_ARTIFACTS = {
    "application",
    "architectures",
    "assets",
    "behavior-ir",
    "callgraph",
    "classes",
    "cpp-object-model",
    "decompilation",
    "frameworks",
    "functions",
    "interaction-model",
    "native-type-flow",
    "objc-dispatch",
    "objc-type-flow",
    "platform-api-map",
    "reconstruction-handoff",
    "recovered-code-index",
    "state-model",
    "strings",
    "ui-model",
    "unresolved",
}
WHEEL_REQUIRED_MEMBERS = {
    "ipalift/__init__.py",
    "ipalift/__main__.py",
    "ipalift/behavior.py",
    "ipalift/cli.py",
    "ipalift/full_run.py",
    "ipalift/handoff.py",
    "ipalift/catalogs/behavior-policy-v1.json",
    "ipalift/catalogs/handoff-policy-v1.json",
    "ipalift/catalogs/interaction-apis-v1.json",
    "ipalift/catalogs/platform-apis-v1.json",
    "ipalift/catalogs/ui-apis-v1.json",
    "ipalift/ghidra_scripts/IPALiftConfigure.java",
    "ipalift/ghidra_scripts/IPALiftHeadless.java",
}
SDIST_REQUIRED_MEMBERS = {
    ".github/workflows/ci.yml",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "LICENSE",
    "MANIFEST.in",
    "README.md",
    "SECURITY.md",
    "docs/architecture.md",
    "docs/release-checklist.md",
    "docs/troubleshooting.md",
    "pyproject.toml",
    "schemas/behavior-ir.schema.json",
    "schemas/reconstruction-handoff.schema.json",
    "schemas/reconstruction-work-packet.schema.json",
    "schemas/state-model.schema.json",
    "scripts/verify-release.py",
    "src/ipalift/behavior.py",
    "src/ipalift/handoff.py",
    "src/ipalift/catalogs/behavior-policy-v1.json",
    "src/ipalift/catalogs/handoff-policy-v1.json",
    "tests/test_behavior.py",
    "tests/test_handoff.py",
    "tests/test_release_contract.py",
}


class VerificationError(RuntimeError):
    """A release gate failed."""


def _run(
    arguments: Iterable[str | os.PathLike[str]],
    *,
    cwd: Path,
    environment: dict[str, str] | None = None,
    expected_exit: int = 0,
    timeout: int = 1200,
) -> subprocess.CompletedProcess[str]:
    rendered = [str(value) for value in arguments]
    try:
        completed = subprocess.run(
            rendered,
            cwd=cwd,
            env=environment,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise VerificationError(f"Could not run {rendered!r}: {exc}") from exc
    if completed.returncode != expected_exit:
        raise VerificationError(
            f"Command returned {completed.returncode}, expected {expected_exit}: {rendered!r}\n"
            f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}"
        )
    return completed


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _validate_member_names(names: Iterable[str], source: str) -> set[str]:
    normalized: set[str] = set()
    for raw_name in names:
        name = raw_name.replace("\\", "/").rstrip("/")
        if not name:
            continue
        path = PurePosixPath(name)
        if path.is_absolute() or ".." in path.parts:
            raise VerificationError(f"{source} contains unsafe archive path: {raw_name}")
        if name.lower().endswith(".ipa"):
            raise VerificationError(f"{source} contains a private IPA input: {raw_name}")
        normalized.add(name)
    return normalized


def audit_distributions(wheel: Path, sdist: Path) -> None:
    with zipfile.ZipFile(wheel) as archive:
        wheel_members = _validate_member_names(archive.namelist(), wheel.name)
    missing_wheel = sorted(WHEEL_REQUIRED_MEMBERS - wheel_members)
    if missing_wheel:
        raise VerificationError(f"Wheel is missing required members: {missing_wheel}")
    if any(name.startswith(("tests/", ".github/", "docs/")) for name in wheel_members):
        raise VerificationError("Wheel contains source-only tests, workflow, or documentation trees")

    with tarfile.open(sdist, "r:gz") as archive:
        for member in archive.getmembers():
            if member.issym() or member.islnk():
                raise VerificationError(f"Source distribution contains a link: {member.name}")
        raw_members = _validate_member_names(
            (member.name for member in archive.getmembers()), sdist.name
        )
    top_levels = {PurePosixPath(name).parts[0] for name in raw_members}
    if len(top_levels) != 1:
        raise VerificationError(f"Source distribution has unexpected roots: {sorted(top_levels)}")
    sdist_members = {
        "/".join(PurePosixPath(name).parts[1:])
        for name in raw_members
        if len(PurePosixPath(name).parts) > 1
    }
    missing_sdist = sorted(SDIST_REQUIRED_MEMBERS - sdist_members)
    if missing_sdist:
        raise VerificationError(f"Source distribution is missing required members: {missing_sdist}")


def _packed_version(major: int, minor: int = 0, patch: int = 0) -> int:
    return (major << 16) | (minor << 8) | patch


def _valid_armv6_macho() -> bytes:
    dylib_path = b"/System/Library/Frameworks/UIKit.framework/UIKit\0"
    dylib_size = (24 + len(dylib_path) + 3) & ~3
    dylib = (
        struct.pack(
            "<IIIIII",
            0xC,
            dylib_size,
            24,
            0,
            _packed_version(1),
            _packed_version(1),
        )
        + dylib_path
    ).ljust(dylib_size, b"\0")
    deployment = struct.pack(
        "<IIII", 0x25, 16, _packed_version(2, 1), _packed_version(2, 1)
    )
    encryption = struct.pack("<IIIII", 0x21, 20, 0, 0, 0)
    main_size = 24
    command_size = 56 + len(dylib) + len(deployment) + len(encryption) + main_size
    code_offset = (28 + command_size + 3) & ~3
    code = struct.pack("<I", 0xE12FFF1E)  # ARM bx lr
    file_size = code_offset + len(code)
    segment = struct.pack(
        "<II16sIIIIiiII",
        0x1,
        56,
        b"__TEXT".ljust(16, b"\0"),
        0x1000,
        0x1000,
        0,
        file_size,
        7,
        5,
        0,
        0,
    )
    main = struct.pack("<IIQQ", 0x80000028, main_size, code_offset, 0)
    commands = segment + dylib + deployment + encryption + main
    header = struct.pack("<IiiIIII", 0xFEEDFACE, 12, 6, 2, 5, len(commands), 1)
    return (header + commands).ljust(code_offset, b"\0") + code


def create_release_fixture(path: Path) -> None:
    info = {
        "CFBundleDisplayName": "IPALift Release Fixture",
        "CFBundleExecutable": "Fixture",
        "CFBundleIdentifier": "test.ipalift.release-fixture",
        "CFBundlePackageType": "APPL",
        "CFBundleVersion": "1.0",
        "MinimumOSVersion": "2.1",
    }
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(
            "Payload/Fixture.app/Info.plist",
            plistlib.dumps(info, fmt=plistlib.FMT_BINARY, sort_keys=True),
        )
        archive.writestr("Payload/Fixture.app/Fixture", _valid_armv6_macho())
        archive.writestr("Payload/Fixture.app/image.png", b"fixture-image")
        archive.writestr("Payload/Fixture.app/config.xml", b"<fixture />")


def _schema_registry(schema_root: Path) -> Registry:
    registry = Registry()
    for path in sorted(schema_root.glob("*.schema.json")):
        contents = json.loads(path.read_text(encoding="utf-8"))
        resource = Resource.from_contents(contents)
        registry = registry.with_resource(contents["$id"], resource)
        registry = registry.with_resource(path.name, resource)
    return registry


def validate_workspace(workspace: Path, schema_root: Path) -> None:
    registry = _schema_registry(schema_root)
    analysis_documents: dict[str, dict] = {}
    for path in sorted((workspace / "analysis").glob("*.json")):
        document = json.loads(path.read_text(encoding="utf-8"))
        artifact = str(document.get("artifact") or "")
        schema_path = schema_root / f"{artifact}.schema.json"
        if not schema_path.is_file():
            raise VerificationError(f"No schema for generated artifact {artifact!r}: {path}")
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        Draft202012Validator(schema, registry=registry).validate(document)
        analysis_documents[artifact] = document
    if set(analysis_documents) != EXPECTED_ANALYSIS_ARTIFACTS:
        missing = sorted(EXPECTED_ANALYSIS_ARTIFACTS - set(analysis_documents))
        extra = sorted(set(analysis_documents) - EXPECTED_ANALYSIS_ARTIFACTS)
        raise VerificationError(f"Unexpected analysis artifact set; missing={missing}, extra={extra}")

    packet_schema = json.loads(
        (schema_root / "reconstruction-work-packet.schema.json").read_text(encoding="utf-8")
    )
    packet_validator = Draft202012Validator(packet_schema, registry=registry)
    packets = sorted((workspace / "handoff" / "work-packets").glob("*.json"))
    if not packets:
        raise VerificationError("Complete run generated no reconstruction work packets")
    for path in packets:
        packet_validator.validate(json.loads(path.read_text(encoding="utf-8")))

    handoff = analysis_documents["reconstruction-handoff"]["facts"]
    referenced_paths = {str(item["path"]) for item in handoff["packet_index"]}
    actual_paths = {
        path.relative_to(workspace).as_posix()
        for path in packets
    }
    if referenced_paths != actual_paths:
        raise VerificationError("Reconstruction manifest packet index does not match packet files")
    for reference in handoff["packet_index"]:
        path = workspace / Path(*str(reference["path"]).split("/"))
        if reference["sha256"] != _sha256(path):
            raise VerificationError(f"Reconstruction packet hash mismatch: {reference['path']}")
    final_report = workspace / "reports" / "reconstruction-handoff-report.md"
    if not final_report.is_file():
        raise VerificationError("Complete run generated no final reconstruction handoff report")


def _workspace_hashes(workspace: Path) -> dict[str, str]:
    return {
        path.relative_to(workspace).as_posix(): _sha256(path)
        for path in sorted(workspace.rglob("*"))
        if path.is_file()
    }


def compare_workspaces(first: Path, second: Path) -> None:
    first_hashes = _workspace_hashes(first)
    second_hashes = _workspace_hashes(second)
    if first_hashes == second_hashes:
        return
    differing = sorted(
        name
        for name in set(first_hashes) | set(second_hashes)
        if first_hashes.get(name) != second_hashes.get(name)
    )
    raise VerificationError(
        "Generated workspaces are not byte-identical: " + ", ".join(differing[:20])
    )


def _environment_python(environment_root: Path) -> Path:
    if os.name == "nt":
        return environment_root / "Scripts" / "python.exe"
    return environment_root / "bin" / "python"


def _environment_cli(environment_root: Path) -> Path:
    if os.name == "nt":
        return environment_root / "Scripts" / "ipalift.exe"
    return environment_root / "bin" / "ipalift"


def verify_installed_artifact(
    artifact: Path,
    *,
    label: str,
    root: Path,
    schema_root: Path,
    fixture: Path,
    ghidra_home: Path | None,
) -> Path | None:
    environment_root = root / f"venv-{label}"
    venv.EnvBuilder(with_pip=True, clear=True).create(environment_root)
    python = _environment_python(environment_root)
    cli = _environment_cli(environment_root)
    clean_environment = dict(os.environ)
    clean_environment.pop("PYTHONPATH", None)
    clean_environment.pop("GHIDRA_HOME", None)
    clean_environment["PYTHONUTF8"] = "1"

    _run(
        [
            python,
            "-m",
            "pip",
            "install",
            "--disable-pip-version-check",
            "--no-deps",
            artifact,
        ],
        cwd=root,
        environment=clean_environment,
    )
    _run([python, "-m", "pip", "check"], cwd=root, environment=clean_environment)
    version = _run([cli, "--version"], cwd=root, environment=clean_environment)
    if version.stdout.strip() != f"ipalift {VERSION}":
        raise VerificationError(f"Unexpected {label} console version: {version.stdout!r}")
    module_version = _run(
        [python, "-m", "ipalift", "--version"], cwd=root, environment=clean_environment
    )
    if module_version.stdout.strip() != f"ipalift {VERSION}":
        raise VerificationError(f"Unexpected {label} module version: {module_version.stdout!r}")
    location = _run(
        [python, "-c", "import pathlib, ipalift; print(pathlib.Path(ipalift.__file__).resolve())"],
        cwd=root,
        environment=clean_environment,
    ).stdout.strip()
    if str(environment_root.resolve()).lower() not in location.lower():
        raise VerificationError(f"{label} imported outside its clean environment: {location}")
    help_result = _run([cli, "--help"], cwd=root, environment=clean_environment)
    for command in ("run-all", "build-handoff"):
        if command not in help_result.stdout:
            raise VerificationError(f"{label} CLI help omits {command}")

    missing = _run(
        [cli, "analyze", root / "missing.ipa", "--output", root / "missing-output"],
        cwd=root,
        environment=clean_environment,
        expected_exit=2,
    )
    if "ipalift: error: Cannot access source IPA" not in missing.stderr:
        raise VerificationError(f"{label} missing-input error is not concise: {missing.stderr!r}")
    if "Traceback" in missing.stderr:
        raise VerificationError(f"{label} exposes a traceback for a user input error")
    timeout_error = _run(
        [cli, "decompile", root / "missing-workspace", "--function-timeout", "0"],
        cwd=root,
        environment=clean_environment,
        expected_exit=2,
    )
    if "--function-timeout must be between 1 and 600 seconds" not in timeout_error.stderr:
        raise VerificationError(f"{label} timeout error is not actionable: {timeout_error.stderr!r}")

    discovery_root = root / f"discovery-{label}"
    fake_home = discovery_root / "tools" / "ghidra" / "ghidra_99.0_PUBLIC"
    (fake_home / "support").mkdir(parents=True)
    (fake_home / "Ghidra").mkdir()
    (fake_home / "support" / "analyzeHeadless.bat").write_text("@echo off\n", encoding="utf-8")
    (fake_home / "support" / "analyzeHeadless").write_text("#!/bin/sh\n", encoding="utf-8")
    (fake_home / "Ghidra" / "application.properties").write_text(
        "application.version=99.0\n", encoding="utf-8"
    )
    discovery = _run(
        [
            python,
            "-c",
            "from ipalift.ghidra import discover_ghidra_home; "
            "print(discover_ghidra_home().version)",
        ],
        cwd=discovery_root,
        environment=clean_environment,
    )
    if discovery.stdout.strip() != "99.0":
        raise VerificationError(f"{label} conventional Ghidra discovery failed")
    configured_environment = dict(clean_environment)
    configured_environment["GHIDRA_HOME"] = str(fake_home)
    configured = _run(
        [
            python,
            "-c",
            "from ipalift.ghidra import discover_ghidra_home; "
            "print(discover_ghidra_home().version)",
        ],
        cwd=root,
        environment=configured_environment,
    )
    if configured.stdout.strip() != "99.0":
        raise VerificationError(f"{label} GHIDRA_HOME discovery failed")

    if ghidra_home is None:
        return None

    first = root / f"workspace-{label}-a"
    second = root / f"workspace-{label}-b"
    for output in (first, second):
        completed = _run(
            [
                cli,
                "run-all",
                fixture,
                "--output",
                output,
                "--ghidra-home",
                ghidra_home,
                "--function-timeout",
                "30",
                "--analysis-timeout",
                "600",
            ],
            cwd=root,
            environment=clean_environment,
            timeout=1200,
        )
        if "[14/14] build-handoff" not in completed.stdout:
            raise VerificationError(f"{label} run-all did not reach the handoff stage")
        validate_workspace(output, schema_root)
    compare_workspaces(first, second)
    return first


def _find_artifacts(dist_dir: Path) -> tuple[Path, Path]:
    wheels = sorted(dist_dir.glob(f"ipalift-{VERSION}-*.whl"))
    sdists = sorted(dist_dir.glob(f"ipalift-{VERSION}.tar.gz"))
    if len(wheels) != 1 or len(sdists) != 1:
        raise VerificationError(
            f"Expected one wheel and one sdist for {VERSION}; found wheels={wheels}, sdists={sdists}"
        )
    return wheels[0].resolve(), sdists[0].resolve()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dist-dir",
        type=Path,
        default=Path("dist"),
        help="directory containing the IPALift 0.1.0 wheel and source distribution",
    )
    parser.add_argument(
        "--ghidra-home",
        type=Path,
        help="optional Ghidra installation; enables full deterministic run-all verification",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    repository_root = Path(__file__).resolve().parents[1]
    schema_root = repository_root / "schemas"
    try:
        wheel, sdist = _find_artifacts(args.dist_dir.resolve())
        audit_distributions(wheel, sdist)
        ghidra_home = args.ghidra_home.resolve(strict=True) if args.ghidra_home else None
        with tempfile.TemporaryDirectory(prefix="ipalift-release-") as temporary:
            root = Path(temporary)
            fixture = root / "release-fixture.ipa"
            create_release_fixture(fixture)
            verified: dict[str, Path | None] = {}
            for label, artifact in (("wheel", wheel), ("sdist", sdist)):
                verified[label] = verify_installed_artifact(
                    artifact,
                    label=label,
                    root=root,
                    schema_root=schema_root,
                    fixture=fixture,
                    ghidra_home=ghidra_home,
                )
            if ghidra_home is not None:
                assert verified["wheel"] is not None and verified["sdist"] is not None
                compare_workspaces(verified["wheel"], verified["sdist"])
        print(f"Wheel: {wheel.name} sha256={_sha256(wheel)}")
        print(f"Source distribution: {sdist.name} sha256={_sha256(sdist)}")
        print("Clean installs: wheel=passed, sdist=passed")
        if ghidra_home is None:
            print("Full run-all: skipped (pass --ghidra-home to enable)")
        else:
            print("Full run-all: wheel=passed twice, sdist=passed twice")
            print("Schemas: passed; deterministic output: passed; cross-artifact output: passed")
        print("RELEASE_VERIFICATION_OK")
        return 0
    except (OSError, ValueError, VerificationError) as exc:
        print(f"release verification failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
